version: '3'
services:
  express-app:
    build: .
    ports: 
      - '3000:3000'
    depends_on: 
      - db
    environment:
      DATABASE_URL: "mongodb://monty:pass@db:27017/mydatabase?authSource=admin&directConnection=true"
    volumes:
      - ./uploads:/app/uploads   # Здесь монтируется папка на хосте в контейнер
  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports:
      - '27017:27017'
    environment: 
      MONGO_INITDB_ROOT_USERNAME: monty 
      MONGO_INITDB_ROOT_PASSWORD: pass

